using Alazani.Domain.Entities.Enums;

namespace Alazani.Domain.Models.Domain
{
    public record UserModel(int Id,
                            string FirstName,
                            string LastName,
                            string EmailAddress,
                            string PhoneNumber,
                            string PrivateNumebr,
                            string UserName,
                            string Password,
                            string Address,
                            int Status,
                            DateTime BirthDate,
                            DateTime StartDate,
                            DateTime EndDate,
                            int OrganizationId,
                            RoleModel? Role,
                            RecordStatusEnum RecordStatus,
                            DateTimeOffset CreateDate,
                            string CreatorUserId);
    public record CreateUserModel(string FirstName,
                                  string LastName,  
                                  string EmailAddress,  
                                  string PhoneNumber,  
                                  string PrivateNumebr,  
                                  string UserName,  
                                  string Password,  
                                  string Address,  
                                  int Status,  
                                  DateTime BirthDate,  
                                  DateTime StartDate,  
                                  DateTime EndDate,  
                                  int OrganizationId,  
                                  int RoleId);  
    public record UpdateUserModel(int Id,
                                  string FirstName,
                                  string LastName,
                                  string EmailAddress,
                                  string PhoneNumber,
                                  string PrivateNumebr,
                                  string UserName,
                                  string Password,
                                  string Address,
                                  int Status,
                                  DateTime BirthDate,
                                  DateTime StartDate,
                                  DateTime EndDate,
                                  int OrganizationId,
                                  int RoleId);
    public record DeleteUserModel(int Id);
}