version: '3.4'

services:
  alazanidb:
    container_name: alazanidb
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=alazanidb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  alazani.api:
    container_name: alazani.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseOptions:ConnectionString=Host=127.0.0.1;Port=5432;Server=alazanidb;Database=alazanidb;User Id=admin;Password=admin1234;"
    ports:
      - "8002:80"
    depends_on:
      - alazanidb



    

