version: '3.4'

services:
  alazanidb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

  alazani.api:
    image: ${DOCKER_REGISTRY-}alazaniapi
    build:
      context: .
      dockerfile: Alazani.API/Dockerfile
      


volumes:
  postgres_data:
  pgadmin_data:  
  portainer_data: